[build]
  command = "npm run build"
  publish = "dist"

# API Proxy - routes /api/* requests to the backend
[[redirects]]
  from = "/api/*"
  to = "https://fhfastapi.onrender.com/:splat"
  status = 200
  force = true

# SPA Support - must come after API proxy
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200